### ISSUE TITLE
开篇virtualenv激活环境

### ISSUE THREAD

**Issue by Easy-wei** [borisliu/from-python-to-django-cms#3]
vscode的控制台现在改为powershell，不再是cmd了，所以激活virtualenv时候要cd到scripts文件下，然后.\activate这样才能激活虚拟环境。之前的办法不行了。

**Comment by Easy-wei** [comment]
很开心遇见你，终于又有一个用vscode做主力写python的同志了。

**Comment by borisliu** [comment]
志同道合啊，我现在主要就是VSCode。
虚拟环境的问题等我校对的时候会确认一下。
